version: '3.8'

services:
  angular-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4201:4201"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production